version: '3.6'
services:
 server:
  build: /home/ubuntu/ohmydawg/back-end/.
  ports:
   - 5000:5000
  networks:
   - ohmydawg
  volumes:
   - ohmydawgData:/home/ubuntu/ohmydawg/back-end/
 reactapp:
  build: /home/ubuntu/ohmydawg/front-end/.
  ports:
   - 3000:3000
  networks:
   - ohmydawg
networks:
 ohmydawg:
volumes:
 ohmydawgData:
  # volumes now makes data persistant.... maybe look at having a file just for saved data now
  # once nginx image is built need to include details in here too