version: '3.6'
services:
 server:
  build: /home/ubuntu/ohmydawg/back-end
  ports:
   - 5000:5000
  volumes:
   - /home/ubuntu/ohmydawg/back-end/accounts.json:/home/ubuntu/data.json
   - /home/ubuntu/ohmydawg/back-end/static/photos/:/home/ubuntu/photos/
  networks:
   - ohmydawg
 reactapp:
  build: /home/ubuntu/ohmydawg/front-end
  ports:
   - 3000:3000
  networks:
   - ohmydawg
networks:
  ohmydawg:
